source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'
use_frameworks!

target 'Education Platform' do
  pod 'Localize-Swift'
  pod 'Fabric'
  pod 'Crashlytics'
  pod 'PureLayout'
  pod 'FontAwesomeKit'
  pod 'PasswordTextField'
  pod 'EAIntroView'
  pod 'IQKeyboardManager'
  pod 'Alamofire'
  pod 'EVReflection'
  pod 'FacebookCore'
  pod 'FacebookLogin'
  pod 'FacebookShare'
  pod 'Google/SignIn'
  pod 'JSQMessagesViewController'
  pod 'Kingfisher'
  pod 'SwiftyJSON'
  pod 'STPopup'
  pod 'Starscream'
  pod 'INSPhotoGallery'
  pod 'DZNEmptyDataSet'
  pod 'M13Checkbox'
  pod 'ESPullToRefresh'
  pod 'SDWebImage'
  pod 'DropDown'
end

